version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: changeMe  # changeMe
      WORDPRESS_DB_NAME: changeme  # changeMe my database Name
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database1
      MYSQL_USER: mysql1
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: _password
    depends_on:
      - db
